version: '3.7'
services:
  ############################################################################################################################
  # FRONTEND APP
  ############################################################################################################################
  ############################################################################################################################
  # POSTGRES
  ############################################################################################################################
  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres:12
    restart: always
    ports: 
      - "5500:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
    networks:
      - gateway
  ############################################################################################################################
  # HASURA
  ############################################################################################################################
  hasura:
    container_name: hasura
    image: hasura/graphql-engine:v1.3.3
    ports:
    - "8080:8080"
    depends_on:
    - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
    networks:
      - gateway
  ############################################################################################################################
  # KINESIS
  ############################################################################################################################
volumes:
  db_data:
networks:
  gateway: {}
