version: '3.7'
services:
  ############################################################################################################################
  # FRONTEND APP
  ############################################################################################################################
  stripe-cli:
    image: stripe/stripe-cli:latest
    container_name: stripe-cli
    environment:
        STRIPE_API_KEY: sk_test_51GxIRlE8hHKqEw8LMuVCSbA9OapYX7beCPDmg2xxzMGmRmH2KL6K03URWrp67rnSKmKfy3Y0SzzpfvfB55s4q9bo00ktTUnEOT
    command: listen --forward-to http://localstack:4566/restapis/${REST_API_ID}/local/_user_request_/stripe-event
  ############################################################################################################################
  # POSTGRES
  ############################################################################################################################
  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres:12
    restart: always
    ports: 
      - "5500:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
    # networks:
    #   - localstack-net
  ############################################################################################################################
  # HASURA
  ############################################################################################################################
  hasura:
    container_name: hasura
    image: hasura/graphql-engine:v1.3.3
    ports:
    - "8080:8080"
    depends_on:
    - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
    # networks:
    #   - localstack-net
  ############################################################################################################################
  # AWS APIGATEWAY, EVENTBRIDGE & LAMBDA
  ############################################################################################################################
  localstack:
    image: localstack/localstack:latest
    ports:
      - '4563-4599:4563-4599'
    environment:
      - SERVICES=lambda,s3,apigateway,cloudformation,secretsmanager,sts,iam,cloudwatch,eventbridge,route53
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
volumes:
  db_data:
