version: '3.7'
services:
  ############################################################################################################################
  # FRONTEND APP
  ############################################################################################################################
  ############################################################################################################################
  # POSTGRES
  ############################################################################################################################
  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres:12
    restart: always
    ports: 
      - "5500:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    # networks:
    #   - localstack-net
  ############################################################################################################################
  # HASURA
  ############################################################################################################################
  hasura:
    container_name: hasura
    build:
      context: ./services/hasura
    ports:
      - '3010:80'
    depends_on:
      - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
    command:
      ['graphql-engine', 'serve', '--server-port', '80', '--enable-console']
    # networks:
    #   - localstack-net
  ############################################################################################################################
  # AWS APIGATEWAY, EVENTBRIDGE & LAMBDA
  ############################################################################################################################
  localstack:
    image: localstack/localstack:latest
    ports:
      - '4563-4599:4563-4599'
    environment:
      - SERVICES=lambda,s3,apigateway,cloudformation,secretsmanager,sts,iam,cloudwatch,events,route53
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
volumes:
  db_data:
