# NOTE: update this with your service name
service: stripe-event

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-localstack

custom:
  localstack:
    host: 'http://localhost'
    stages:
      - local
    debug: true
    region: us-east-1
    endpointFile: localstack_endpoints.json

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  environment:
    LOCALSTACK_HOSTNAME: localhost
    STRIPE_API_KEY: sk_test_51GxIRlE8hHKqEw8LMuVCSbA9OapYX7beCPDmg2xxzMGmRmH2KL6K03URWrp67rnSKmKfy3Y0SzzpfvfB55s4q9bo00ktTUnEOT
  apiGateway:
    minimumCompressionSize: 1024,
    shouldStartNameWithService: true
    
  # To load environment variables externally
  # rename env.example to .env and uncomment
  # the following line. Also, make sure to not
  # commit your .env.
  #
  #environment:
  #  SAMPLE_ENV_VAR: ${env:SAMPLE_ENV_VAR}

functions:
  stripeEventHandler: 
    handler: stripeEventHandler.handler
    events:
      - http:
          method: post
          path: stripe-event
#   stripeTransactionHandler:
#     handler: stripeTransactionHandler.process
#     description: Processes transaction events from stripe
#     events:
#       - eventBridge:
#         eventBus: stripe
#         pattern:
#           source:
#             - stripe.transactions
